# Generated by Django 3.1.6 on 2021-05-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuego', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='stock',
            field=models.IntegerField(default=50, verbose_name='Unidades'),
            preserve_default=False,
        ),
    ]
