# Generated by Django 3.1.6 on 2021-05-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210318_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
